import type { Metadata } from "next";
import "@/styles/globals.scss";
import '@/lib/fontawesome';
import styles from "@/styles/layout.module.scss";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "AppleDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
